project:
  type: website

website:
  site-url: https://nanoyan.github.io/p00/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/p00/
  navbar:
    logo: iqb-logo-black.png
    search: true
    left:
      - href: index.qmd
        text: "IQB Testprofil 2"
    right:
      - icon: github
        href: https://github.com/nanoyan/p00
        aria-label: Source Code
  sidebar:
    style: "docked"
    lang: de
    collapse-level: 2
    contents:
      - href: output/Deutsch.qmd
        text: "de"
        lang: de
      - href: output/Englisch.qmd
        text: "en"
        lang: en    
      - href: output/Franzoesisch.qmd
        text: "fr"
        lang: fr
      - href: output/Italienisch.qmd
        text: "it"
        lang: it
      - href: output/Raetoromanisch.qmd
        text: "rm"
        lang: en                     


lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
