project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p00/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://iqb-vocabs.github.io/p00/
  navbar:
    logo: iqb-logo-black.png
    search: true
    left:
      - href: index.qmd
        text: "IQB Testprofil"
    right:
      - icon: github
        href: https://iqb-vocabs.github.io/p00
        aria-label: Source Code
  sidebar:
    style: "docked"
    lang: de
    collapse-level: 2
    contents:
      - href: output/Deutsch.qmd
        text: "Deutsch"
        lang: de
      - href: output/Englisch.qmd
        text: "Englisch"
        lang: en    
      - href: output/Franzoesisch.qmd
        text: "Französisch"
        lang: fr
      - href: output/Italienisch.qmd
        text: "Italienisch"
        lang: it
      - href: output/Raetoromanisch.qmd
        text: "Rätoromanisch"
        lang: en                     


lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
